# Generated by Django 3.2.9 on 2021-11-28 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_auto_20211128_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='descripton',
            field=models.TextField(max_length=200),
        ),
    ]
